### ISSUE TITLE
Design Doc Public Request

### ISSUE THREAD

**Issue by sharego** [dcos/dcos-diagnostics#172]
Hi,  [the design doc](https://docs.google.com/document/d/1UU47_ZVBPQRzzSc9D57W4h7VtzRyMxiLTcZ4XKfwA5I/edit?usp=sharing) now it is served by Google Docs,  access need a permission proved,  the permission  can be set to anybody read?

**Comment by janisz** [comment]
Fixed https://docs.google.com/document/d/1UU47_ZVBPQRzzSc9D57W4h7VtzRyMxiLTcZ4XKfwA5I/edit?usp=sharing
